# Generated by Django 5.2.8 on 2025-11-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_media_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('code_veridied', 'code_veridied'), ('done', 'done')], default='new', max_length=20),
        ),
    ]
